{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3/1.5.0-alpha23/material3-1.5.0-alpha23.module",
    "group": "androidx.compose.material3",
    "module": "material3",
    "version": "1.5.0-alpha23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0",
      "buildId:": "15722354"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.5.0-alpha23"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.5.0-alpha23"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha23"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3.aar",
          "url": "material3-android-1.5.0-alpha23.aar",
          "size": 4619539,
          "sha512": "8476e0ef4acca3f7e66143fb120348f485d3d327f43604444c17058ba519d4ca6333781de09c3b78914574fd357853b307b478dcdece0b1db0a2541a60c0e274",
          "sha256": "b1e18bd3059242e322839d47cab1a96682d21fa55e986cb79f864002f3a4f7ae",
          "sha1": "d064ad2d1a495eb8986416f3fd22ff69fa3338f2",
          "md5": "1fbac7d0d7e1689ca19a4a9ecbcc377d"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.5"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.5.0-alpha23"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.5.0-alpha23"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha23"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3.aar",
          "url": "material3-android-1.5.0-alpha23.aar",
          "size": 4619539,
          "sha512": "8476e0ef4acca3f7e66143fb120348f485d3d327f43604444c17058ba519d4ca6333781de09c3b78914574fd357853b307b478dcdece0b1db0a2541a60c0e274",
          "sha256": "b1e18bd3059242e322839d47cab1a96682d21fa55e986cb79f864002f3a4f7ae",
          "sha1": "d064ad2d1a495eb8986416f3fd22ff69fa3338f2",
          "md5": "1fbac7d0d7e1689ca19a4a9ecbcc377d"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.5.0-alpha23"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.5.0-alpha23"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.5.0-alpha23"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-android-1.5.0-alpha23-sources.jar",
          "url": "material3-android-1.5.0-alpha23-sources.jar",
          "size": 896805,
          "sha512": "ca74835b176ff916a5148e6eaf5671350d097626632ffea61ff3952ea010b417f8702c3fef8ffc357b54a92baba07d6b2fc353e959c48db51d3340e5a1283124",
          "sha256": "2a3f6e21e0309edfc44b7afe2029ce741b6662bb81038a534ed6e285ab10e735",
          "sha1": "e52928c2813fa2c44c3647365432ff0e952a14b8",
          "md5": "2396f1b48231bb878d4c01db50c4a720"
        },
        {
          "name": "material3-1.5.0-alpha23-samples-sources.jar",
          "url": "material3-android-1.5.0-alpha23-samples-sources.jar",
          "size": 107207,
          "sha512": "f8ec273026b3a91b5d08813595ea0f12f0776d945cbe116d43eadae28ce7cc0d147cad07a3920e1277011325d7644b06a247254b4793605ca2b760e201df62c3",
          "sha256": "590e981aace4afaa08be4e20199f1ac71e2462c62c20899e423d1490ddec76d7",
          "sha1": "bf5ade2f39376ac11ae0e752c225b70404622eae",
          "md5": "8af4ca5cf43f52d801fc6a5a22902b64"
        }
      ]
    }
  ]
}